[project]
name = "yatc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "bs4>=0.0.2",
    "protego>=0.6.0",
    "readability-lxml>=0.8.4.1",
]
